DariShop/AdminLte/Pages/AddToBasket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using DariShop.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DariShop.Pages
{
    [Authorize]
    public class AddToBasketModel : PageModel
    {
        private AppDbContext _context;
        public List<BasketViewModel> _basket;
        public int _priceSum;
        public AddToBasketModel(AppDbContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            _basket = _context.ProductBasket
                .Include(x => x.Product)
                .Select(x => new BasketViewModel
                {
                    ProductName = x.ProductName,
                    Count = x.Count,
                    Price = x.Product.Price,
                    Id = x.Id
                }).ToList();

          //  _basket = _context.ProductBasket.Include(x=>x.Product).ToList();

            _priceSum = _basket.Sum(x => x.Price * x.Count);
        }

        public async Task<IActionResult> OnGetAddToBasket(int productId)
        {
            var product = _context.Products.SingleOrDefault(x => x.Id == productId);

            var productExistInBasket = _context.ProductBasket.SingleOrDefault(x => x.ProductId == productId);
            if (productExistInBasket == null)
            {
                var newBasket = new ProductBasket { ProductId = product.Id, ProductName = product.Name, Count = 1};
                _context.ProductBasket.Add(newBasket);
            }
            else
            {
                productExistInBasket.Count++;
            }

            product.Count--;
            _context.Products.Update(product);

            _context.SaveChanges();
            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnGetDelete(int id)
        {
            var productBasket = _context.ProductBasket.SingleOrDefault(x => x.Id == id);
            int productsCount = productBasket.Count;
            int productId = productBasket.ProductId;
            _context.ProductBasket.Remove(productBasket);
            var product = _context.Products.SingleOrDefault(x => x.Id == productId);
            if (product != null)
            {
                product.Count += productsCount;
            }
            _context.SaveChanges();
            return RedirectToPage("/AddToBasket");
        }

        public async Task<IActionResult> OnGetPay()
        {
            var allBaskets = _context.ProductBasket.Include(x=>x.Product).ToList();

            foreach (var basket in allBaskets)
            {
                var newHistory = new History()
                {
                    ProductId = basket.ProductId,
                    DateSold = DateTime.Now,
                    Count = basket.Count,
                    ProductName = basket.ProductName,
                    ProductPrice = basket.Product.Price
                };
                _context.Histories.Add(newHistory);
            }

            _context.ProductBasket.RemoveRange(allBaskets);
            _context.SaveChanges();

            return RedirectToPage("/Index");
        }
    }
}

DariShop/AdminLte/Pages/Cash.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DariShop.Pages
{
    [Authorize]
    public class CashModel : PageModel
    {
        public List<History> _basketHistory;
        public int Sum;
        public int Count;
        public int Profit;
        public int CustomerSalary;
        public CashModel(AppDbContext context)
        {
            _context = context;
        }

        private readonly AppDbContext _context;
        public void OnGet()
        {
            _basketHistory = _context.Histories
                .Include(x => x.Product)
                .GroupBy(x=>x.ProductName)
                .Select(cl => new History
                {
                    ProductName = cl.Key,
                    ProductPrice = cl.Sum(x=>x.ProductPrice*x.Count),
                    Count = cl.Sum(x=>x.Count)
                }).ToList();

            int mainCostSum = _context.Histories.Include(x => x.Product).Sum(x => x.Product.MainCost * x.Count);
            Sum = _context.Histories.Include(x => x.Product).Sum(x => x.Product.Price * x.Count);
            Count = _context.Histories.Include(x => x.Product).Sum(x => x.Count);
            Profit = Sum - mainCostSum;
            CustomerSalary = (Sum / 100) * 5;
        }
    }
}

DariShop/AdminLte/Pages/CreateProduct.cshtml.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using DariShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DariShop.Pages
{
    [Authorize]
    public class CreateProductModel : PageModel
    {
        IHostingEnvironment _appEnvironment;
        private AppDbContext _context;

        //Dependency Injection - внедрение зависимостей
        public CreateProductModel(IHostingEnvironment appEnvironment, AppDbContext context)
        {
            _appEnvironment = appEnvironment;
            _context = context;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(ProductModel model)
        {
            string path = Path.Combine(_appEnvironment.WebRootPath, "Images");
            
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            // загрузка файлов в папку wwwroot
            path = Path.Combine(path, model.Image.FileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await model.Image.CopyToAsync(fileStream);
            }

            var rootImageUrl = "http://127.0.0.1:3131";
            var imageUrl = Path.Combine(rootImageUrl, model.Image.FileName);
            var newProduct = new Product
            {
                Name = model.Name,
                Price = model.Price,
                MainCost = model.MainPrice,
                Count = model.Count,
                ImagePath = imageUrl,
                CreateDate = DateTime.Now
            };

            _context.Products.Add(newProduct);
            _context.SaveChanges();

            return Redirect("/Index");
        }
    }
}

DariShop/AdminLte/Pages/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using DariShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DariShop.Pages
{
    [Authorize]
    public class EditProductModel : PageModel
    {
        public Product _product;
        private AppDbContext _context;
        private IHostingEnvironment _appEnvironment;
        public EditProductModel(AppDbContext context, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }
        public void OnGetEdit(int id)
        {
            _product = _context.Products.SingleOrDefault(x => x.Id == id);
        }

        public async Task<IActionResult> OnPost(ProductModel model)
        {
            var existProduct = _context.Products.SingleOrDefault(x => x.Id == model.Id);

            existProduct.Name = model.Name;
            existProduct.MainCost = model.MainPrice;
            existProduct.Price = model.Price;
            existProduct.Count = model.Count;

            if (model.Image != null)
            {
                string path = Path.Combine(_appEnvironment.WebRootPath, "Images");

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                // загрузка файлов в папку wwwroot
                path = Path.Combine(path, model.Image.FileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await model.Image.CopyToAsync(fileStream);
                }

                var rootImageUrl = "http://127.0.0.1:3131";
                var imageUrl = Path.Combine(rootImageUrl, model.Image.FileName);
                existProduct.ImagePath = imageUrl;
            }

            _context.Products.Update(existProduct);
            _context.SaveChanges();

            return RedirectToPage("/Index");
        }
    }
}

DariShop/AdminLte/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DariShop.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DariShop/AdminLte/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DariShop.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly AppDbContext _context;
        public List<Product> Products { get; set; }

        public IndexModel(ILogger<IndexModel> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {
            Products = _context.Products.ToList();
        }


        //Обработчик для удаления товара
        public async Task<IActionResult> OnGetDelete(int id)
        {
            var product = _context.Products.SingleOrDefault(x => x.Id == id);

            _context.Products.Remove(product);
            _context.SaveChanges();
            return RedirectToPage("/Index");
        }

        public void OnPost(string searchParam)
        {
            if (string.IsNullOrEmpty(searchParam))
            {
                Products = _context.Products.ToList();
            }
            else
            {
                Products = _context.Products.Where(x => x.Name.Contains(searchParam)).ToList();
            }
        }
    }
}

DariShop/AdminLte/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DariShop.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DariShop/AdminLte/Pages/RegistrationRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DariShop.Pages
{
    [Authorize]
    public class RegistrationRequestModel : PageModel
    {
        public RegistrationRequestModel(AppDbContext context)
        {
            _context = context;
        }

        private readonly AppDbContext _context;
        public List<RegistrationRequest> RegistrationRequests { get; set; }
        public void OnGet()
        {
            RegistrationRequests = _context.RegistrationRequests.ToList();
        }
    }
}

DariShop/AdminLte/Pages/Stats.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DariShop.Entities;
using DariShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DariShop.Pages
{
    [Authorize]
    public class StatsModel : PageModel
    {
        public List<StatsViewModel> saleStats;
        public List<History> SoldProducts;
        private readonly AppDbContext _context;
        public ChartResponseModel chartResponse;
        public int SoldProductCount;
        public int ProfitSum;
        public StatsModel(AppDbContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            //saleStats = _context.ProductBasket
            //    .Include(x => x.Product)
            //    .Where(x => x.IsSold)
            //    .Select(x => new StatsViewModel()
            //    {
            //        Profit = x.Product.Price - x.Product.MainCost * x.Count,
            //        DateTime = x.DateSold
            //    }).ToList();
            var now = DateTime.Now;
            SoldProductCount = _context.Histories.Sum(x => x.Count);
            int mainCostSum = _context.Histories.Include(x => x.Product).Sum(x => x.Product.MainCost * x.Count);
            int sum = _context.Histories.Include(x => x.Product).Sum(x => x.Product.Price * x.Count);
            ProfitSum = sum - mainCostSum;

            SoldProducts = _context.Histories
                .Include(x => x.Product)
                .Where(x => x.DateSold.Month == now.Month && x.DateSold.Year == now.Year)
                .GroupBy(x => x.ProductName)
                .Select(cl => new History
                {
                    ProductName = cl.Key,
                    DateSold = cl.Max(x=>x.DateSold),
                    Count = cl.Sum(x => x.Count)
                })
                .Take(10)
                .ToList();
        }

        public JsonResult OnGetGetInfo()
        {

            var dateTimeNow = DateTime.Now;
            int currentMonth = dateTimeNow.Month;
            int currentYear = dateTimeNow.Year;

            var firstDayOfMonth = new DateTime(dateTimeNow.Year, dateTimeNow.Month, 1);
            var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);

            var infoForCurrentMonth = _context.Histories
                .Include(x => x.Product)
                .Where(x => x.DateSold.Month == currentMonth && x.DateSold.Year == currentYear)
                .ToList();


            var chartDto = new List<Chart>();
            for (int i = 0; i < lastDayOfMonth.Day; i++)
            {
                var info = new Chart()
                {
                    DayNumber = i + 1
                };
                var date = new DateTime(currentYear, currentMonth, i + 1);
                info.SaleCount = infoForCurrentMonth.Count(x => x.DateSold.Date == date.Date);
                chartDto.Add(info);
            }

            chartResponse = new ChartResponseModel()
            {
                yearNumber = currentYear,
                monthNumber = currentMonth,
                numberOfOrders = chartDto
            };

            return new JsonResult(chartResponse);
        }

    }
}

DariShop/AdminLte/Pages/AddToBasket.cshtml
@page
@model DariShop.Pages.AddToBasketModel
@{
}

<div class="text-center">
    <table class="table table-success table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название товара</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        
        @{
            foreach (var item in Model._basket)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.ProductName</td>
                    <td>@item.Price</td>
                    <td>@item.Count</td>
                    <td><a asp-page-handler="Delete" asp-route-id="@item.Id">Удалить</a></td>
                </tr>
            }
        }

        </tbody>
    </table>
    
    <a asp-page-handler="Pay" class="btn btn-outline-secondary">Оплатить</a>

    <h3>Итог: @Model._priceSum</h3>
</div>

DariShop/AdminLte/Pages/Cash.cshtml
@page
@model DariShop.Pages.CashModel
@{
}
<div class="text-center">
    <table class="table table-success table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название товара</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Количество</th>
            </tr>
        </thead>
        <tbody>

        @{
            int counter = 1;
                foreach (var item in Model._basketHistory)
                {
                    <tr>
                        <th scope="row">@counter</th>
                        <td>@item.ProductName</td>
                        <td>@item.ProductPrice</td>
                        <td>@item.Count</td>
                    </tr>
                    counter++;
                }
            }

        </tbody>
    </table>

    <h3>Итоговое количество: @Model.Count</h3>
    <h3>Итоговая сумма: @Model.Sum</h3>
    <h3>Прибыль: @Model.Profit</h3>
    <h3>Зп сотрудникам: @Model.CustomerSalary</h3>
</div>

DariShop/AdminLte/Pages/CreateProduct.cshtml
@page
@model DariShop.Pages.CreateProductModel
@{
}

<div>
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="productName" class="form-label">Название товара</label>
            <input name="Name" type="text" class="form-control" id="productName" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Цена</label>
            <input name="Price" type="number" class="form-control" id="price">
        </div>
        <div class="mb-3">
            <label for="mainCost" class="form-label">Себестоимость</label>
            <input name="MainPrice" type="number" class="form-control" id="mainCost">
        </div>
        <div class="mb-3">
            <label for="count" class="form-label">Количество</label>
            <input name="Count" type="number" class="form-control" id="count">
        </div>
        <div class="mb-3">
            <label for="image" class="form-label">Картинка</label>
            <input id="image" name="Image" type="file" />
        </div>
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
</div>

DariShop/AdminLte/Pages/EditProduct.cshtml
@page
@model DariShop.Pages.EditProductModel
@{
}

<div>
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="productName" class="form-label">Название товара</label>
            <input value="@Model._product.Name" name="Name" type="text" class="form-control" id="productName" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Цена</label>
            <input value="@Model._product.Price" name="Price" type="number" class="form-control" id="price">
        </div>
        <div class="mb-3">
            <label for="mainCost" class="form-label">Себестоимость</label>
            <input value="@Model._product.MainCost" name="MainPrice" type="number" class="form-control" id="mainCost">
        </div>
        <div class="mb-3">
            <label for="count" class="form-label">Количество</label>
            <input value="@Model._product.Count" name="Count" type="number" class="form-control" id="count">
        </div>
        <div class="mb-3">
            <label for="image" class="form-label">Картинка</label>
            <div style="height: 200px; width: 200px;"><img style="width: 100%; height: 100%;" src="@Model._product.ImagePath" /></div>
            <input id="image" name="Image" type="file" />
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>

DariShop/AdminLte/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Цена</th>
                <th scope="col">Себестоимость</th>
                <th scope="col">Количество</th>
                <th scope="col">Картинка</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        
        @{
            foreach (var item in Model.Products)
            {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>@item.MainCost</td>
                        <td>@item.Count</td>
                        <td><div style="height: 90px; width: 90px;"><img style="width: 100%; height: 100%;" src="@item.ImagePath" /></div></td>
                        <td>@if (item.Count != 0)
                        {<a asp-page="AddToBasket" asp-page-handler="AddToBasket" asp-route-productId="@item.Id">Добавить в корзину</a>}</td>
                        <td><a asp-page="EditProduct" asp-page-handler="Edit" asp-route-id="@item.Id">Редактировать</a></td>
                        <td><a asp-page-handler="Delete" asp-route-id="@item.Id">Удалить</a></td>
                    </tr>
            }
        }

        </tbody>
        
        <a asp-page="CreateProduct">Добавить товар</a>
        
        <div class="input-group input-group-lg">
            <form method="post">
                <button style="border: 0" type="submit"><span class="input-group-text" id="search">Поиск</span></button>
                <input name="searchParam" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">
            </form>
        </div>
    </table>
</div>

DariShop/AdminLte/Pages/RegistrationRequest.cshtml
@page
@model DariShop.Pages.RegistrationRequestModel
@{
}

<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Имя пользователя</th>
        <th scope="col">Почта</th>
        <th scope="col">Роль</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    
    <tbody>
        
    @{
        @*foreach (var item in Model.RegistrationRequests)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.MainCost</td>
                <td>@item.Count</td>
                <td><div style="height: 90px; width: 90px;"><img style="width: 100%; height: 100%;" src="@item.ImagePath" /></div></td>
                <td>@if (item.Count != 0)
                    {<a asp-page="AddToBasket" asp-page-handler="AddToBasket" asp-route-productId="@item.Id">Добавить в корзину</a>}</td>
                <td><a asp-page="EditProduct" asp-page-handler="Edit" asp-route-id="@item.Id">Редактировать</a></td>
                <td><a asp-page-handler="Delete" asp-route-id="@item.Id">Удалить</a></td>
            </tr>
        }*@
    }

    </tbody>
</table>

DariShop/AdminLte/Pages/Stats.cshtml
@page
@model DariShop.Pages.StatsModel
@{
}


<div class="w3-animate-left">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Статистика продаж</h5>
                    <div class="float-right">
                        <div class="btn-group">
                            @*<button id="chart-today-button" type="button" class="btn btn-xs btn-white active">Today</button>
                                <button type="button" class="btn btn-xs btn-white">Monthly</button>
                                <button type="button" class="btn btn-xs btn-white">Annual</button>*@
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="flot-chart">
                        <div class="flot-chart-content" id="flot-dashboard-chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <div class="col-lg-3">
            <ul class="stat-list">
                <li>
                    <h2 class="no-margins"></h2>
                    <small>Общее количество продаж</small>
                    <div class="stat-percent">
                            @Model.SoldProductCount
                        </div>
                        @*<div class="progress progress-mini">
                            <div style="width: 44%;" class="progress-bar"></div>
                        </div>*@
                </li>
                <li>
                    <h2 class="no-margins "></h2>
                    <small>Общая прибыль</small>
                    <div class="stat-percent">
                            @Model.ProfitSum
                        </div>
                        @*<div class="progress progress-mini">
                            <div style="width: 23%;" class="progress-bar"></div>
                        </div>*@
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2 class="no-margins">Топ товаров проданных в этом месяце</h2>
            <small>Топ 10</small>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th id="testid" scope="col">Название товара</th>
                        <th scope="col">Дата продажи</th>
                        <th scope="col">Количество</th>
                    </tr>
                </thead>
                <tbody>
                @{
                    int counter = 1;
                        foreach (var item in Model.SoldProducts)
                        {
                            <tr class="table-info">
                                <th scope="row">@counter</th>
                                <td><a asp-Page="/News/GetNews" asp-route-id="@counter">@item.ProductName</a></td>
                                <td>@item.DateSold</td>
                                <td>@item.Count</td>
                            </tr>
                            counter++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section Scripts{
    <script src="/lib/sparkline/jquery.sparkline.min.js"></script>
    <script src="/lib/flot/jquery.flot.js"></script>
    <script src="/lib/flot/jquery.flot.tooltip.min.js"></script>
    <script src="/lib/flot/jquery.flot.resize.js"></script>
    <script src="/lib/flot/jquery.flot.pie.js"></script>
    <script src="/lib/flot/jquery.flot.time.js"></script>
    <script src="/lib/flot/jquery.flot.spline.js"></script>
    <script src="/js/Charts.js"></script>
}